name: GitHub Pages

on:
  push:
    branches:
      - main  # Set a branch to deploy
  pull_request:

jobs: 
  setup:
    runs-on: ubuntu-latest
    steps:
    - name: Hugo setup
      uses: peaceiris/actions-hugo@v2.4.13     
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Build Hugo
      uses: lowply/build-hugo@v0.92.1
      
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
    - name: Hugo Publish
      uses: avinassh/hugo-publish@0.0.1

